name: Deploy to Truenas 112
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:

env:
  TRUENAS_DEPLOY: "true"
  MQTT_BROKER: "10.25.0.112"

jobs:
  Build-ESP8266-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Install Python and pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv

      - name: Set Up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install platformio

      # Compile ESP8266 firmware using PIO inside venv
      - name: Build ESP8266 Firmware
        run: |
          source venv/bin/activate
          pio run
          
      # Find and Upload the Compiled Firmware as an Artifact
      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp8266-firmware
          path: .pio/build/*/firmware.bin

  Notifications:
    runs-on: ubuntu-latest
    needs: [Build-ESP8266-Firmware]
    if: always()
    steps:
      - name: Sanitize Repository Name
        run: |
          REPO_FULL_NAME="${{ gitea.repository }}"  # Example: "owner/repository"
          
          # Extract only the repository name
          REPO_NAME=$(echo "$REPO_FULL_NAME" | awk -F/ '{print $2}')
          
          # Sanitize the repository name
          SANITIZED_NAME=$(echo "$REPO_NAME" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]')
          
          echo "Original Repository Name: $REPO_NAME"
          echo "Sanitized Repository Name: $SANITIZED_NAME"
          
          # Export as an environment variable
          echo "SANITIZED_NAME=$SANITIZED_NAME" >> $GITHUB_ENV     

      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Install Python and pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv

      - name: Set Up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests paramiko

      - name: Send notification to Gotify
        run: |
          source venv/bin/activate
          python3 .gitea/.scripts/notify.py "${{ gitea.ref }}" "${{ job.status }}" "$SANITIZED_NAME"
